apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  imagePullSecrets:
    - name: regcred  # make sure this secret exists
  containers:
    - name: mysql
      image: 807683106441.dkr.ecr.us-east-1.amazonaws.com/mysql@sha256:d1db8a98edc47a92dcf5405c31a29f1294fc365e
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
