apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: employees
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: webapp
      image: 807683106441.dkr.ecr.us-east-1.amazonaws.com/webapp@sha256:d1db8a98edc47a92dcf5405c31a29f1294fc365e
      ports:
        - containerPort: 8080
      env:
        - name: DBHOST
          value: "mysql"           # matches your MySQL service name
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "password"        # make sure this matches MYSQL_ROOT_PASSWORD in mysql-pod
        - name: DBPORT
          value: "3306"
