apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: webapp
          image: 807683106441.dkr.ecr.us-east-1.amazonaws.com/webapp:d1db8a98edc47a92dcf5405c31a29f1294fc365e
          ports:
            - containerPort: 5000
          env:
            - name: DBHOST
              value: "mysql"       # must match the service name
            - name: DBUSER
              value: "root"
            - name: DBPWD
              value: "password"
            - name: DATABASE
              value: "employees"
            - name: DBPORT
              value: "3306"
